### ISSUE TITLE
Validation issue with allowNew on Safari and Chrome Mobile

### ISSUE THREAD

**Issue by dtanase** [lekoala/bootstrap5-tags#73] opened 2023-02-23 11:15 UTC
Hello 

When using the select with allowNew: true (so that the user can define her own tags) the validation is broken on Safari (desktop and mobile) and Chrome Mobile (but not on desktop) so that one has to input minimum to 2 tags to pass the 'required' validation.

The issue is very easily reproducible with the code below, by inputing just one tag.

It works just fine on Chrome Desktop, Firefox Desktop and Edge desktop. Just Safari and Chrome Mobile seem to be broken.

Any ideas what can it be? 

Thank you,
Dorian

```
<!DOCTYPE html>
<html lang="en" class="no-js" data-bs-theme="">
<head>
    <title>Test</title>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" rel="stylesheet">
    <script crossorigin="anonymous" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>

    <script type="module">
        import Tags from "./tags.js";

        Tags.init("#validationTags", {
            clearLabel: "Clear tag",
            allowClear: true,
            allowNew: true,
            suggestionThreshold: 0,
        });

    </script>
</head>

<body>
<div class="container">
    <form method="get" action="https://vercel-dumper.vercel.app/">
        <div class="row mb-3 g-3">
            <div class="col-md-4">
                <label for="validationTags" class="form-label">Tags</label>
                <div class="position-relative has-validation">
                    <select class="form-select" id="validationTags" name="tags[]" multiple required>

                    </select>
                    <div class="invalid-tooltip">Please select a valid tag.</div>
                </div>
            </div>
        </div>
        <br/>
        <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit-id-submit">
    </form>
</div>
</body>
</html>
```

**Comment by lekoala** [comment] 2023-02-23 13:24
@dtanase ah yes there has been a couple of issues with validation lately :-)
i made some updates on master, here is a codepen with your code
https://codepen.io/lekoalabe/pen/bGxeqqr

does that look better?

you can also disable native validation tooltips if needed

**Comment by dtanase** [comment] 2023-02-23 13:39
Hey :-) 

Thank you for the answer!

Yes, issues, especially on the "new IE" (aka Safari)...

But no, the changes do not bring much, still the same error when just one tag is given (see below). However, I noticed that if one adds two tags, then removes one of them, then it works.


![image](https://user-images.githubusercontent.com/17724363/220922527-6610c33b-41f3-4bfb-9e6d-83ce50f21b92.png)

**Comment by lekoala** [comment] 2023-02-23 16:15
@dtanase wow i just tried on my ipad, and safari is really just doing its own thing. even with regular options!
you have to add two options, and after that, even clearing everything, it will still show as valid.
selectedOptions returns empty => it fails to be noticed by required attr
some options are selected in the html => its marked as invalid

i have no clues on how to proceed from there, it's just not following any standard behaviour

**Comment by lekoala** [comment] 2023-02-24 08:53
@dtanase a good night's sleep was the answer :-)
so yes, safari for mobile is just a crazy piece of s... oftware. But if you fully replace the content of the select element, it will pick the changes.
https://codepen.io/lekoalabe/pen/RwYRmYM
this seems to be working. Can you confirm?

**Comment by dtanase** [comment] 2023-02-27 08:56
Hello @lekoala 

I managed to test it and it seems to work!! 🥳 

However, there is a little new "feature", somehow the addition assignment kills the value of `url` here: 
https://github.com/lekoala/bootstrap5-tags/blob/cd75ccf76167198ad34bbe19e79497d6d4339f0c/tags.js#L778

Thank you very much!

**Comment by lekoala** [comment] 2023-02-27 09:42
@dtanase yes, it's wrong code from a recent PR, I have cleaned it up this morning :)
release will follow soon when I can confirm that pending issues have been solved

**Closed by lekoala** 2023-02-27 09:42 UTC
